import Head from "next/head";
import "./globals.css";
import Provider from "./Provider";

export const metadata = {
  title: "TaxLine BD",
  description: "Generated by TaxLine BD",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Head>
          <link rel="manifest" href="/manifest.json" />
          <meta name="theme-color" content="#10B981" />
        </Head>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
